stages:
  - Test

default:
  cache:
    key: global
    policy: pull-push
    paths:
      - node_modules/

test:
  image: node:carbon
  stage: Test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - yarn
    - yarn lint
    - yarn test
    - yarn build
